<?php
// module/Mp3/view/Mp3/Mp3/index.phtml:
$title = 'My Mp3s';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('mp3', array('action'=>'add'));?>">Add new mp3</a>
</p>
<table class="table">
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>Postion</th>
		<th>Mp3file</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($Mp3s as $Mp3) : ?>
	<?php 
	// echo "<pre>";
	// var_dump($Mp3); 
	// echo "</pre>";
	?>
	<tr>
		<td><?php echo $this->escapeHtml($Mp3->title);?></td>
		<td><?php echo $this->escapeHtml($Mp3->area);?></td>
		<td><?php echo $this->escapeHtml($Mp3->position);?></td>
		<td><?php echo $this->escapeHtml($Mp3->mp3file);?></td>
		<td>
			<a href="<?php echo $this->url('mp3',
			array('action' => 'edit', 'id' => $mp3->id));?>">Edit</a>
<a href="<?php echo $this->url('mp3',
array('action' => 'delete', 'id' => $mp3->id));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>