<?php
for ($i = 0; $i < count($this->mp3TagArrayTmp) - 1; $i++) {
	echo '<audio src="'.$this->basePath() .'/data/audio/shandong.ogg#t=' . $this->mp3TagArrayTmp[$i] . ',' . $this->mp3TagArrayTmp[$i + 1] . '"  controls >';
	echo 'audio is not supported.';
	echo '</audio><br />';
	echo $i+1 ;
	// echo '<button name="button'.$i.'" type="button" onclick="alert(\'Hello world!\')">Buggy Whipp Bio</button> <br />';
}

