<?php
// module/Album/view/mp3/mp3/edit.phtml:
$title = 'Edit mp3';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'cms',
	array(
		'action' => 'edit',
		'id'
		=> $this->id,
		)
	));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('area'));
echo $this->formRow($form->get('mp3'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
