<?php
// module/Quiz/view/quiz/quiz/delete.phtml:
$title = 'Delete quiz';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete
	'<?php echo $this->escapeHtml($quiz->title); ?>' by
	'<?php echo $this->escapeHtml($quiz->area); ?>'?
</p>
<?php
$url = $this->url('quiz', array(
	'action' => 'delete',
	'id'
	=> $this->id,
	));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $quiz->id; ?>" />
			<input type="submit" name="del" value="Yes" />
			<input type="submit" name="del" value="No" />
		</div>
	</form>
