<tr>
	<td>
		<a href="<?php echo $this->url('bug',
		array('action'=>'edit', 'id' => $bug->id));?>">Edit</a>
<a href="<?php echo $this->url('bug',
array('action'=>'delete', 'id' => $bug->id));?>">Delete</a>
</td>
<td><?php echo date('m/d/y', $this->date); ?></td>
<td><?php echo $this->priority; ?></td>
<td><?php echo $this->status; ?></td>
<td><?php echo $this->url; ?></td>
<td><?php echo $this->author; ?></td>
<td><?php echo $this->description; ?></td>
</tr>
