<?php
// module/Album/view/album/album/index.phtml:
$title = 'My Bugs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('bug', array('action'=>'submit'));?>">Add new bug</a>
</p>
<table class="table">
	<tr>
		<th>Author</th>
		<th>email</th>
		<th>date</th>
		<th>url</th>
		<th>description</th>
		<th>priority</th>
		<th>status</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($bugs as $bug) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($bug->author);?></td>
		<td><?php echo $this->escapeHtml($bug->email);?></td>
		<td><?php echo $this->escapeHtml($bug->date);?></td>
		<td><?php echo $this->escapeHtml($bug->url);?></td>
		<td><?php echo $this->escapeHtml($bug->description);?></td>
		<td><?php echo $this->escapeHtml($bug->priority);?></td>
		<td><?php echo $this->escapeHtml($bug->status);?></td>
		<td>
			<a href="<?php echo $this->url('bug',
			array('action'=>'edit', 'id' => $bug->id));?>">Edit</a>
<a href="<?php echo $this->url('bug',
array('action'=>'delete', 'id' => $bug->id));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>
