<?php
// module/Album/view/album/album/add.phtml:
$title = 'Add new mp3';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('lesson', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('area'));
// echo $this->formRow($form->get('image-file-name'));
echo $this->formRow($form->get('mp3'));

        // $fileElement = $form->get('image-file');
        // echo $this->formRow($fileElement);
        // echo $this->formLabel($fileElement); 
        // echo $this->formFile($fileElement); 
        // echo $this->formElementErrors($fileElement); 


echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>
