<?php
// module/Album/view/album/album/index.phtml:
$title = 'My Mp3s';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('lesson', array('action'=>'add'));?>">Add new mp3</a>
</p>
<table class="table">
	<tr>
		<th>Title</th>
		<th>area</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($mp3s as $mp3) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($mp3->title);?></td>
		<td><?php echo $this->escapeHtml($mp3->artist);?></td>
		<td>
			<a href="<?php echo $this->url('lesson',
			array('action'=>'edit', 'id' => $mp3->id));?>">Edit</a>
<a href="<?php echo $this->url('lesson',
array('action'=>'delete', 'id' => $mp3->id));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>
