INSERT INTO `album` (`artist`, `title`)
VALUES
('Various Artists', 'Mum - The Ultimate Mothers Day Collection'),
	('One Direction', 'Up All Night'),
	('Bon Jovi', 'Bon Jovi Greatest Hits'),
	('Agnetha Fltskog', 'A'),
	('Fun.', 'Some Nights'),
	('Justin Bieber', 'Believe Acoustic'),
	('Atoms for Peace', 'Amok'),
	('Justin Timberlake', 'Justified'),
	('Passenger', 'All the Little Lights'),
	('Kodaline', 'The High Hopes EP'),
	('Lana Del Rey', 'Born to Die'),
	('JAY Z & Kanye West', 'Watch the Throne (Deluxe Version)'),
	('Biffy Clyro', 'Opposites'),
	('Various Artists', 'Return of the 90s'),
	('Gabrielle Aplin', 'Please Don\'t Say You Love Me - EP'),
	('Various Artists', '100 Hits - Driving Rock'),
	('Jimi Hendrix', 'Experience Hendrix - The Best of Jimi Hendrix'),
	('Various Artists', 'The Workout Mix 2013'),
	('The 1975', 'Sex'),
	('Chase & Status', 'No More Idols'),
	('Rihanna', 'Unapologetic (Deluxe Version)'),
	('The Killers', 'Battle Born'),
	('Olly Murs', 'Right Place Right Time (Deluxe Edition)'),
	('A$AP Rocky', 'LONG.LIVE.A$AP (Deluxe Version)'),
	('Various Artists', 'Cooking Songs'),
	('Haim', 'Forever - EP'),
	('Lianne La Havas', 'Is Your Love Big Enough?'),
	('Michael Bubl', 'To Be Loved'),
	('Daughter', 'If You Leave'),
	('The xx', 'xx'),
	('Eminem', 'Curtain Call'),
	('Kendrick Lamar', 'good kid, m.A.A.d city (Deluxe)'),
	('Michael Bubl', 'Crazy Love (Hollywood Edition)'),
	('Bon Jovi', 'Bon Jovi Greatest Hits - The Ultimate Collection'),
	('Rita Ora', 'Ora'),
	('g33k', 'Spabby'),
	('Various Artists', 'Annie Mac Presents 2012'),
	('David Bowie', 'The Platinum Collection'),
	('Bridgit Mendler', 'Ready or Not (Remixes) - EP'),
	('Dido', 'Girl Who Got Away'),
	('Various Artists', 'Now That\'s What I Call Disney'),
	('The 1975', 'Facedown - EP'),
	('Kodaline', 'The Kodaline - EP'),
	('Various Artists', '100 Hits: Super 70s'),
	('Fred V & Grafix', 'Goggles - EP'),
	('Biffy Clyro', 'Only Revolutions (Deluxe Version)'),
	('Train', 'California 37'),
	('Ben Howard', 'Every Kingdom (Deluxe Edition)'),
	('Various Artists', 'Motown Anthems'),
	('Courteeners', 'ANNA'),
	('Johnny Marr', 'The Messenger'),
	('Rodriguez', 'Searching for Sugar Man'),
	('Jessie Ware', 'Devotion'),
	('Bruno Mars', 'Unorthodox Jukebox'),
	('Various Artists', 'Call the Midwife (Music From the TV Series)'
);
