<div class="hero-unit">
  <h1><?php echo sprintf($this->translate('Welcome to %s99做题采编系统%s'), '<span class="zf-green">', '</span>') ?></h1>
<!--     <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
  <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p> -->
</div>

<div class="row">

  <div class="span4">
    <h2><?php echo $this->translate('历届考题') ?></h2>
    <p><?php echo sprintf($this->translate('各省市历届听力考试题目')); ?></p>
    <p><a class="btn btn-success" href=<?php  echo $this->url('mp3'); ?>  target="_blank"><?php echo $this->translate('考题') ?> &raquo;</a></p>
  </div>

  <div class="span4">
    <h2><?php echo $this->translate('考题录入') ?></h2>
    <p><?php echo sprintf($this->translate('请老师录入考试题目'), '<a href="http://zf2-test/quiz/add">', '</a>') ?></p>
    <p><a class="btn btn-success" href="http://zf2-test/quiz/add" target="_blank"><?php echo $this->translate('录入') ?> &raquo;</a></p>
  </div>

  <div class="span4">
   <h2><?php echo $this->translate('语音编辑') ?></h2>
   <p><?php echo sprintf($this->translate('编辑英语听力mp3文件'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
   <p><a class="btn btn-success" href="http://zf2-test/quiz/edit" target="_blank"><?php echo $this->translate('编辑') ?> &raquo;</a></p>
 </div>
</div>
